AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: dijoteji-s3buckets
      # BucketName: vamsi-bucket-12345
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
